### ISSUE TITLE
Set GPU for mining

### ISSUE THREAD

**Issue by dsalodki** [FinMiner/FinMiner#10]
Can I set only the first GPU of two for mining?

**Comment by FinMiner** [comment]
There is no built-it feature for that but you can run miner on several selected cards using CUDA feature. Just set up CUDA_VISIBLE_DEVICES environment variable. In case there are 2 cards and you'd like to mine on first one, run miner in a following manner on Windows (you can do .bat file for this):
```
set CUDA_VISIBLE_DEVICES=0
finminer.exe
```
For Linux:
```
CUDA_VISIBLE_DEVICES=0 ./finminer
```

**Comment by FinMiner** [comment]
GPU selection will be added as a core feature in next release.
