### ISSUE TITLE
failed to init cuda platform

### ISSUE THREAD

**Issue by Jorapama** [FinMiner/FinMiner#13]
My finminer does not work.
![failed](https://user-images.githubusercontent.com/43591096/46049695-26d11000-c106-11e8-8a24-1757f154360d.JPG)
I've already uninstalled the Nvidia driver and reinstalled it and still gives this same error, even in different versions of the finminer.

I have 1x 1050Ti.

**Comment by FinMiner** [comment]
Thanks for reporting! Please check our [2.2.4 release](https://github.com/FinMiner/FinMiner/releases/tag/v2.2.4) - issue with new driver is fixed in it.

**Comment by Jorapama** [comment]
This new version worked, thank you for the help!
