### ISSUE TITLE
Devices do not work for CPU mining

### ISSUE THREAD

**Issue by insperedia** [FinMiner/FinMiner#20]
It would be nice to have a possibility to limit mining to fewer cores then CPU has

**Comment by FinMiner** [comment]
We have cpuThreads option for this. Feel free to set it to any number from 1 to the number of cores.

**Comment by insperedia** [comment]
set cpuThreads to 28, finMiner showed it on initialization, but all threads are in use.
![image](https://user-images.githubusercontent.com/1706065/48700274-ef558000-ebeb-11e8-9ce7-89b57c07c618.png)

**Comment by FinMiner** [comment]
Interesting. Havent't tested on such processor but probably it's because of hardware cores implementation. Try setting 16 cpuThreads. If it loads processor 100%, cpuThreads=14 should give you same effect as 28/32.
