### ISSUE TITLE
std::system_error - Resource temporarily unavailable

### ISSUE THREAD

**Issue by eric-saintetienne** [FinMiner/FinMiner#23]
After switching out from devfee the miner crashes with the following output (from systemd):
```
Nov 21 22:06:32 debian spawn-finminer[653]: PascalCoin: CPU: 865.032 H/s
Nov 21 22:07:02 debian spawn-finminer[653]: 2018-11-21 22:07:02: ~~~~~~ DevFee begin ~~~~~~
Nov 21 22:07:04 debian spawn-finminer[653]: PascalCoin - Total speed: 861.084 H/s, Total shares: 71 Rejected: 0, Time: 01:37:22
Nov 21 22:07:04 debian spawn-finminer[653]: PascalCoin: CPU: 861.084 H/s
Nov 21 22:07:35 debian spawn-finminer[653]: PascalCoin - Total speed: 857.771 H/s, Total shares: 71 Rejected: 0, Time: 01:37:53
Nov 21 22:07:35 debian spawn-finminer[653]: PascalCoin: CPU: 857.771 H/s
Nov 21 22:07:35 debian spawn-finminer[653]: PascalCoin last 10 min - Total: 861.647 H/s.
Nov 21 22:07:39 debian spawn-finminer[653]: 2018-11-21 22:07:39: ~~~~~~ DevFee end ~~~~~~
Nov 21 22:07:39 debian spawn-finminer[653]: terminate called after throwing an instance of 'std::system_error'
Nov 21 22:07:39 debian spawn-finminer[653]:   what():  Resource temporarily unavailable
```

Systemd automatically restarts `finminer` which works for a while and eventually terminates again with the same error message: `Resource temporarily unavailable`, symptomatic of a system call returning ` EAGAIN` and not being properly handled in the code.

In any case the output of `std::sterror()` seems too little for you to figure what's happening. More insight is likely needed regarding the resource in question and the operation in progress. How can I help you debug this? Maybe there is a hidden option that activates more verbose debug logging, for example.

My config file (redacted):
```
wallet=XXXXX-XX
paymentId=YYYYYYYYYYYYYYYY
algorithm=RandomHash
coin=PASC
email=ZZZZZZZZ@ZZZZ.ZZZ
noLog=true
cpuThreads=0
pool1 = pasc-eu1.nanopool.org:15556
pool2 = pasc-eu2.nanopool.org:15556
pool3 = pasc-us-east1.nanopool.org:15556
pool4 = pasc-us-west1.nanopool.org:15556
pool5 = pasc-asia1.nanopool.org:15556
``` 

Notes:

- All other lines in the config file are either commented or blank,
- No GPU avaiable, only CPU mining,
- `noLog` is set because I prefer logging through systemd, using ` journalctl`, but unsetting it doesn't affect this issue,
- I can reproduce this issue on other machines running the same OS (debian 9) with the same config file.

Thank you

**Comment by eric-saintetienne** [comment]
I have this issue on baremetal.

**Comment by FinMiner** [comment]
Thanks a lot. Looks like some Debian 9 specific issue, will try to reproduce.

**Comment by eric-saintetienne** [comment]
I've run it with strace and during 30 minutes of mining there was about 2,000 occurences of `EAGAIN`.

The ones that were just before the program crashed are those:
```
finminer.2559:11:12:30.174118 read(12, 0xc4202e1000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
finminer.2559:11:12:30.715122 read(12, 0xc4202e1000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
finminer.2559:11:12:31.718220 read(12, 0xc4202e1000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
finminer.2559:11:12:32.727776 read(12, 0xc4202e1000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
finminer.2559:11:12:33.775241 read(12, 0xc4202e1000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
finminer.2559:11:12:34.835435 read(12, 0xc4202e1000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
finminer.2559:11:12:35.827967 read(12, 0xc4202e1000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
finminer.2559:11:12:36.842283 read(12, 0xc4202e1000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
finminer.2559:11:12:37.883236 read(12, 0xc4202e1000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
finminer.2559:11:12:38.923223 read(12, 0xc4202e1000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
finminer.2559:11:12:39.900672 read(12, 0xc4202e1000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
```

This happenned again when returning from devfee mining:
```
2018-11-22 12:35:11: ~~~~~~ DevFee begin ~~~~~~
PascalCoin - Total speed: 756.017 H/s, Total shares: 42 Rejected: 0, Time: 01:30:05
PascalCoin: CPU: 756.017 H/s
2018-11-22 12:35:31: PascalCoin - SHARE FOUND (CPU, nonce: 597288043).
PascalCoin: Share denied (320 ms).
2018-11-22 12:35:47: ~~~~~~ DevFee end ~~~~~~
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
```

**Comment by eric-saintetienne** [comment]
I've run it with `strace -tt -ff -D -o /tmp/fminer ./fminer` and it recorded a number of `EAGAIN` (about 2000 in 30 minutes time), but none just before the crash which hapenned when switching back from devfee again.

**Comment by eric-saintetienne** [comment]
I've noticed that all commands, even `/bin/ls` returned _Resource temporarily unavailable_ until `finminer` crashes, then everything goes back to normal. Maybe it's simply a limits issue... number of file descriptors or number of processes maybe.

**Comment by khwong77** [comment]
I have this issue too not VM is the main machine. DevFee end terminate called after throwing an instance of 'std::system_error' I am mining Pascal on RandomHash . Every damn day i need to restart the Finminer , can anyone help me ? i am really have no clue. Thanks

**Comment by FinMiner** [comment]
Thanks you for your active support! We've reproduced and (hopefully) fixed this issue. Used to be a threads leak. Please have a look at ours new [FinMiner 2.4.2 release](https://github.com/FinMiner/FinMiner/releases/tag/v2.4.2)

**Comment by eric-saintetienne** [comment]
Thanks mate, I'm trying it right now and will let you know if the badness still occurs.

**Comment by nikmit** [comment]
I am running the new code now, after 25 min no crashes but my new average hash rate is 1.8K, where before it was 2K... I guess if it eliminates the downtime will average out the same.

**Comment by khwong77** [comment]
I had downloaded and trying now hopefully everything goes well. Very efficient thank you for the new updates.
