### ISSUE TITLE
stop at "Setting up algorithm: RandomHash"

### ISSUE THREAD

**Issue by wowbin** [FinMiner/FinMiner#24]

**Comment by FinMiner** [comment]
This looks like some network issue. What OS are you running? Does miner stop every time you run it or just sometimes? Does it work with other Internet connection / firewall disabled?

**Comment by FinMiner** [comment]
Please try running our latest [version 2.4.4](https://github.com/FinMiner/FinMiner/releases/tag/v2.4.4).
