### ISSUE TITLE
Stale shares - linux

### ISSUE THREAD

**Issue by salvo2002** [FinMiner/FinMiner#28]
OS: Linux 4.13.16-hiveos (0.6-05@181204-4)
Pool: https://www.hiveon.net/
Motherboard: PRIME Z270-A
CPU: Intel Celeron G3930 @ 2.90GHz
GPUs: 6 x RX570 8Gb & 4 x RX580 8Gb
Driver: AMDGPU Pro 18.10-572953

Tested out Finminer 2.4.4 on HiveOS. I immediately noticed an increase in stale shares vs. PhoenixMiner 4.0b.

This same issue happened when PhoenixMiner released their linux version. It was traced back to the miner not recognizing or not tuned for the OpenCL driver installed. PhoenixMiner fixed the issue and the stale shares were significantly reduced.

![capture](https://user-images.githubusercontent.com/10107638/49535301-abfc4200-f878-11e8-803b-90916fe5e5f4.PNG)

[log.txt](https://github.com/FinMiner/FinMiner/files/2650070/log.txt)

**Comment by FinMiner** [comment]
Thanks for detailed feedback. Stale shares fixed on [release 2.4.6](https://github.com/FinMiner/FinMiner/releases/tag/v2.4.6) with a small hashrate degradation possible on AMD cards. Will try to fix both stales and hashrate on next major release.
