### ISSUE TITLE
set memory clock 

### ISSUE THREAD

**Issue by mahosseini** [FinMiner/FinMiner#30]
hi 
how can i set memory clock with finminer ?
i have 12 1050ti nvidia in each my etherum mining rig .
tnx

**Comment by FinMiner** [comment]
It's currently not implemented in miner. We recommend using MSI Afterburner on Windows and custom linux builds with overclocking scripts. Maybe we will add this feature however on some next release of miner which was rebranded to [nanominer](https://github.com/nanopool/nanominer/)

**Comment by mahosseini** [comment]
Great. it's very important because i use 12 GPU on my each miner rig and Afterburner dosen't work more than 8 GPU ,
i'll waiting for your next release.

**Comment by FinMiner** [comment]
[Nanominer](https://github.com/nanopool/nanominer/releases) has `coreClocks`, `memClocks` options now to support Nvidia cards overclocking.
