### ISSUE TITLE
finminer exe closed itself

### ISSUE THREAD

**Issue by haydut023** [FinMiner/FinMiner#4]
hi i have similar problem could you help me?

version 2.0.5
2018-06-18 NVML error failed to get device handle by PCI : 0:1:0
using default configration file : config.ini
2018-06-18 single device detected
GPU#0: platform CUDA Name Quadro M3000M 4096 mb available

after few minutes later , program closed itself.

Waiting for your valuable replies

Thanks in advance.

**Comment by haydut023** [comment]
is anyone there?

**Comment by FinMiner** [comment]
Hi! Does FinMiner put some logs to `logs` folder? Looks strange cause after printing device info miner prints configuration then connects to pool and starts mining. Could you please provide a config.ini file (you can remove you actual wallets if you'd like not to show them) ?
Also, this is unofficial suport channel. For 24/7 support you can send an email to support@miner.finom.io.
Your GPU seems to be fine with it's 5.0 compute capability.

**Comment by FinMiner** [comment]
Please check newer 2.1.1 version. It has more verbose logs for some known usecases like unsupported driver version or device arch.
