### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by jtktam** [FinMiner/FinMiner#5]
Is there TLS support or plan to add it? thanks!

**Comment by FinMiner** [comment]
Hello! We actually have TLS support for pool connections. Please report if there are some issues on any pool. Buut this thould work generally.

**Comment by jtktam** [comment]
tested against ethermine tls pools and it doesn't work.  is it working only against nanopool?

**Comment by FinMiner** [comment]
Thanks for reporting. Will try to fix.

**Comment by FinMiner** [comment]
Should work on latest 2.2.1 release now.
