### ISSUE TITLE
crash on ubuntu cuda 9.2

### ISSUE THREAD

**Issue by toptim** [FinMiner/FinMiner#6]
`terminate called after throwing an instance of 'std::system_error'
  what():  mmap'ing file: Cannot allocate memory
Aborted (core dumped)`

**Comment by FinMiner** [comment]
This means insufficient memory. Please try adding swap memory to increase virtual address space. The amount of memory would be size of DAG (~2.5 GB) * number of GPUs for Ethereum mining.

**Comment by toptim** [comment]
not have so much ram or disk free :(
