### ISSUE TITLE
failed to init cuda platform

### ISSUE THREAD

**Issue by jameyt** [FinMiner/FinMiner#8]
windows 10

version 2.1.2
cuda driver version is 9.2, runtime version is 8.0
nvml error: failed to get device handle by pci: 0:10:0
nvml error: failed to get device handle by pci: 0:10:0
failed to init cuda platform.

2 1080 TIs installed on this computer

config:

; FinMiner configuration file.
; Lines starting with ";" are comments.
; Full configuration file description and examples can be
; found in ReadMe document.

; Address to send funds to.
wallet=wallet address omitted

; Payment ID (for exchange accounts). Otherwise do not set up or leave empty.
;paymentId=

; (Optional) Mining algorithm.
; Supported values: Ethash, Cryptonight
algorithm=Cryptonight

; (Optional) Coin to mine.
; Supported values: ETH, ETC, XMR, ETN.
coin=XMR

; (Optional) Rig (worker) name.
rigName=rig name omitted

; (Optional) Email to send notifications to (for nanopool).
email=email omitted

; (Optional) Mining pools. By default nanopool is used.
;pool1 = eth-eu1.nanopool.org:9999
;pool2 = eth-eu2.nanopool.org:9999
;pool3 = eth-us-east1.nanopool.org:9999
;pool4 = eth-us-west1.nanopool.org:9999
;pool5 = eth-asia1.nanopool.org:9999
;pool6 = eth-jp1.nanopool.org:9999
;pool7 = eth-au1.nanopool.org:9999

**Comment by FinMiner** [comment]
Thanks for reporting. Do you have SLI enabled for this two cards?

**Comment by FinMiner** [comment]
Please disable SLI in NVIDIA Control Panel. This should fix the issue. See #7
